name: تجهيز الموقع لاستضافة Hostinger

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-prepare:
    runs-on: ubuntu-latest
    
    steps:
    - name: تحميل الكود
      uses: actions/checkout@v4
      
    - name: إعداد Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: تنصيب المكتبات
      run: npm ci
      
    - name: بناء المشروع
      run: npm run build
      
    - name: إعداد ملفات Hostinger
      run: |
        # نسخ ملف .htaccess إلى مجلد البناء
        cp public/.htaccess dist/
        
        # التأكد من وجود ملف index.html
        ls -la dist/
        
        # إنشاء ملف zip للاستضافة
        cd dist
        zip -r ../almashhadsky-hostinger.zip .
        cd ..
        
        # عرض محتويات الملف المضغوط
        echo "محتويات الملف المضغوط:"
        unzip -l almashhadsky-hostinger.zip | head -20
        
    - name: رفع ملف الاستضافة
      uses: actions/upload-artifact@v4
      with:
        name: almashhadsky-hostinger
        path: almashhadsky-hostinger.zip
        retention-days: 30
        
    - name: رفع مجلد البناء الكامل
      uses: actions/upload-artifact@v4
      with:
        name: dist-folder
        path: dist/
        retention-days: 30